[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Security-Policy = "base-uri 'self'; default-src 'self'; style-src 'self' 'unsafe-inline' fonts.googleapis.com use.typekit.net cdn.giesela.app; script-src 'self' 'unsafe-inline' use.typekit.net cdn.giesela.app; font-src 'self' fonts.gstatic.com use.typekit.net fonts.typekit.net; img-src 'self' p.typekit.net cdn.giesela.app; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests; report-uri https://thesarogroup.report-uri.com/r/d/csp/enforce; report-to groupname"
Expect-CT = "enforce, max-age=604800, report-uri=\"http://thesarogroup.report-uri.com/r/d/ct/reportOnly\""
Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block; report=https://thesarogroup.report-uri.com/r/d/xss/enforce"
Vary = "Accept-Encoding"
